import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/Sidebar";

const inter = Poppins({
	weight: ["400", "500", "600"],
	subsets: ["latin"],
	style: ["normal"],
});

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
	icons: "./../public/favicon.ico",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} container`}>
				<Sidebar />
				<main className="main">{children}</main>
			</body>
		</html>
	);
}
